Implementa integração API dos itens do cardápio dos restaurantes
devpass-tech/challenge-mvvm-delivery pull request #45
Opened 2022-05-18 18:46 UTC by luiza-cora

Descrição

✨ Implementado a integração com a API de itens do cardápio de um restaurante.

Checklist:

[x] Não adiciona código duplicado
[x] Não contém código comentado
[x] Não contém código WIP

Evidências da feature:

<img width="750" alt="image" src="https://user-images.githubusercontent.com/97253467/169122575-e6b41675-5315-47db-a98b-15441212ed8a.png">

2022-05-18 22:08 UTC, reisdev commented on solutions/devsprint-matheus-reis-2/DeliveryAppChallenge/Models/MenuItemDetails.swift
> +struct MenuItemDetails: Codable {
Como o recurso retornado é um item do menu com seus detalhes, o nome do Model poderia ser apenas `MenuItem`. O que acha?

2022-05-18 22:29 UTC, luiza-cora commented on solutions/devsprint-matheus-reis-2/DeliveryAppChallenge/Models/MenuItemDetails.swift
> +struct MenuItemDetails: Codable {
Acho justo 😁

2022-05-23 14:58 UTC, reisdev requested changes

2022-05-23 14:58 UTC, reisdev commented on solutions/devsprint-matheus-reis-2/DeliveryAppChallenge/Service/DeliveryApi.swift
> +    func fetchMenuItem(_ name: String, _ completion: @escaping (Result<MenuItemDetails, DeliveryApiError>) -> Void)
Assim como nos demais métodos, o parâmetro `name` não é mais necessário. E, dentro do método, ao invés de passar o `name` como argumento para o método `request`, você passaria o `Endpoints.menuItemDetails`

2022-05-23 14:58 UTC, reisdev commented on solutions/devsprint-matheus-reis-2/DeliveryAppChallenge/Service/DeliveryApi.swift
> +        self.request(name, completion: completion)
Como citado no outro comentário, removendo o parâmetro `name` do seu método, deve-se passar o `Endpoints.menuItemDetails`  para o método `request`.
```suggestion
        self.request(Endpoints.menuItemDetails, completion: completion)
```

2022-05-24 22:45 UTC, reisdev approved these changes

2022-05-24 22:46 UTC, merged