Implementar navegação para Tela de Lista de Restaurantes
devpass-tech/challenge-mvvm-delivery pull request #49
Opened 2022-05-23 21:08 UTC by marianamai

2022-05-24 01:45 UTC, reisdev requested changes
A implementação está correta. Senti falta apenas de uma evidência, como uma gravação de tela, para demonstrar o comportamento implementado.

2022-05-24 19:58 UTC, marianamai commented
https://user-images.githubusercontent.com/94709718/170121427-850e541a-712f-4cf7-8061-778a57bab834.mp4

2022-05-24 19:58 UTC, marianamai commented
https://user-images.githubusercontent.com/94709718/170121427-850e541a-712f-4cf7-8061-778a57bab834.mp4

2022-05-24 20:00 UTC, reisdev approved these changes

2022-05-25 01:31 UTC, reisdev commented on solutions/devsprint-matheus-reis-2/DeliveryAppChallenge/Screens/Components/CategoryListView/CategoryCellView.swift
> +        if let topViewController = UIApplication.shared.keyWindow?.rootViewController as? UINavigationController {
Essa implementação tem 2 problemas:

- O atributo `keyWindow` foi depreciado
- A view não deveria ter a responsabilidade pela navegação.

Nesse caso, pode ser aplicado o padrão de Coordinator, que foi visto durante a nossa sprint.

2022-05-25 01:33 UTC, reisdev requested changes

2022-05-25 01:33 UTC, reisdev commented on solutions/devsprint-matheus-reis-2/DeliveryAppChallenge/Screens/Components/CategoryListView/CategoryCellView.swift
> +        let tap = UITapGestureRecognizer(target: self, action: #selector(tap))
Esse trecho não deveria estar no método `addSubviews`, e sim no `configureAdditionalBehaviors`

2022-07-26 13:36 UTC, closed without merging