Passa a ViewModel implementada para a ViewController
devpass-tech/challenge-mvvm-delivery pull request #51
Opened 2022-05-24 19:40 UTC by tandersonf

Descrição simples da nova feature
✨ implementa corretamente a ViewModel na Controller.
Altera a inicialização da viewModel da View para a ViewController e faz as alterações necessárias.

Checklist:
[x] Não adiciona código duplicado
[x] Não contém código comentado
[x] Não contém código WIP

2022-05-25 01:55 UTC, reisdev requested changes

2022-05-25 01:55 UTC, reisdev commented on solutions/devsprint-matheus-reis-2/DeliveryAppChallenge/Screens/Settings/SettingsView.swift
> +    private weak var delegate: SettingsViewControllerProtocol?
Entendi sua motivação para usar o delegate nesse caso. Porém, temos dois problemas:

- O `delegate`deve ser atribuído por quem instancia a classe, e não passado como um parâmetro pro `init`

Abaixo, um exemplo de como ficaria:

```swift
let settingsView = SettingsView()
settingsView.delegate = self
```
E exatamente por isso ele não pode ser um atributo `private`.

- Os dados deveriam ser obtidos e preenchidos pela ViewController, e não pela própria view

A view não deveria ter ciência da viewModel diretamente. Você poderia usar o conceito do delegate com um método, que recebe a chave para ser obtido o valor no `UserDefaults`. Você pode seguir o mesmo conceito usado pelo @pedrotres na `RestaurantListView`. Nesse caso, o delegate se chamaria `SettingsViewDelegate`

2022-05-25 01:55 UTC, reisdev commented on solutions/devsprint-matheus-reis-2/DeliveryAppChallenge/Screens/Settings/SettingsView.swift
> +            cell.textLabel?.text = delegate?.getName()
Como citado no comentário anterior, seu delegate poderia ter apenas um método `getInfo`, que retornaria as strings desejadas de acordo com a chave informada.

2022-05-26 02:40 UTC, reisdev requested changes

2022-05-26 02:40 UTC, reisdev commented on solutions/devsprint-matheus-reis-2/DeliveryAppChallenge/Screens/Settings/SettingsView.swift
> +    weak var delegate: SettingsViewControllerDelegate?
O `delegate`, nesse caso, seria da `SettingsView`, como eu havia comentado anteriormente, e não da ViewController. Logo, o protocolo deveria estar juntamente com a SettingsView, e deveria ser chamado `SettingsViewDelegate`

2022-05-26 15:02 UTC, reisdev requested changes

2022-05-26 15:02 UTC, reisdev commented on solutions/devsprint-matheus-reis-2/DeliveryAppChallenge/Screens/Settings/SettingsViewController.swift
> +    func getInfo(key: SettingsViewModel.UserInfoData) -> String {
O ideal é fazer a extensão separadamente da implementação da própria classe. Ficaria dessa forma:

```swift
extension SettingsViewController: SettingsViewDelegate {
    func getInfo(key: SettingsViewModel.UserInfoData) -> String {
        return viewModel.getInfo(for: key)
    }
}
```

Fazendo assim fica mais fácil identificar quais métodos são parte da extensão.

2022-05-26 15:03 UTC, tandersonf commented on solutions/devsprint-matheus-reis-2/DeliveryAppChallenge/Screens/Settings/SettingsViewController.swift
> +    func getInfo(key: SettingsViewModel.UserInfoData) -> String {
blz 👍

2022-05-26 22:38 UTC, reisdev approved these changes

2022-05-26 22:38 UTC, merged