Feature/Menu service request
devpass-tech/challenge-mvvm-delivery pull request #59
Opened 2022-08-10 11:58 UTC by vitor-rc1

### Descrição e Solução
- Menu service request
 
### Checklist:
- [x] Não adiciona código duplicado
- [x] Não contém código comentado
- [x] Não contém código WIP
- [ ] Teste Unitário Implementado

2022-08-10 12:43 UTC, reisdev requested changes

2022-08-10 12:43 UTC, reisdev commented on solutions/devsprint-matheus-reis-3/DeliveryAppChallenge/Service/Delivery/DeliveryApi.swift
> +        networkManager.get(DeliveryApiRequest.fetchRestaurantDetail.urlRequest) { (result: Result<RestaurantDetails, ServiceError>) in
O endpoint correto para essa tarefa seria o `fetchMenuItem`. Inclusive, subi uma correção nos endpoints, então você irá precisar sincronizar sua branch com a `main`.

2022-08-10 22:38 UTC, vitor-rc1 commented on solutions/devsprint-matheus-reis-3/DeliveryAppChallenge/Service/Delivery/DeliveryApi.swift
> +        networkManager.get(DeliveryApiRequest.fetchRestaurantDetail.urlRequest) { (result: Result<RestaurantDetails, ServiceError>) in
Opa Matheus. Falha minha no codigo, vou ajustar já.
No notion está errado também, vou ajustar lá

2022-08-10 22:50 UTC, vitor-rc1 commented on solutions/devsprint-matheus-reis-3/DeliveryAppChallenge/Service/Delivery/DeliveryApi.swift
> +        networkManager.get(DeliveryApiRequest.fetchRestaurantDetail.urlRequest) { (result: Result<RestaurantDetails, ServiceError>) in
Feito

2022-08-10 23:55 UTC, reisdev commented on solutions/devsprint-matheus-reis-3/DeliveryAppChallenge/Models/Menu.swift
> +struct Menu: Codable {
Seria mais interessante nomear esse model como `MenuItem`, já que o método é `fetchMenuItem`

2022-08-11 01:00 UTC, reisdev approved these changes

2022-08-11 01:00 UTC, reisdev commented
Favor resolver os conflitos de merge

2022-08-11 20:11 UTC, merged