Feature/address search view model
devpass-tech/challenge-mvvm-delivery pull request #61
Opened 2022-08-11 23:59 UTC by vitor-rc1

### Descrição e Solução
- Address view search view model
 
### Checklist:
- [x] Não adiciona código duplicado
- [x] Não contém código comentado
- [x] Não contém código WIP
- [ ] Teste Unitário Implementado
 
### Evidências:
| Preview |
| ------ |
| ![Simulator Screen Recording - iPod touch (7th generation) - 2022-08-11 at 20 52 11](https://user-images.githubusercontent.com/42953452/184261342-93f6206b-fe57-4fe9-967c-a51917d76b33.gif)  |

2022-08-12 14:58 UTC, reisdev requested changes

2022-08-12 14:58 UTC, reisdev commented on solutions/devsprint-matheus-reis-3/DeliveryAppChallenge/Screens/Components/AddressListView/AddressListView.swift
> +    private let dataSource: AddressListDataSource
Para evitar problemas com retain cycles, é interessante que essa propriedade seja definida como `weak var`

2022-08-12 14:58 UTC, reisdev commented on solutions/devsprint-matheus-reis-3/DeliveryAppChallenge/Screens/Settings/SettingsViewController.swift
> +    let api = DeliveryApi()
A API não deveria estar na camada de UI, e sim na ViewModel

2022-08-12 14:58 UTC, reisdev commented on solutions/devsprint-matheus-reis-3/DeliveryAppChallenge/Screens/Settings/SettingsViewController.swift
> +        api.fetchSearchAddresses { result in
Imagino que essa linha tenha sido inserida apenas para teste e pode ser removida, assim como a propriedade `api` da `SettingsViewController`.

2022-08-12 15:06 UTC, vitor-rc1 commented on solutions/devsprint-matheus-reis-3/DeliveryAppChallenge/Screens/Settings/SettingsViewController.swift
> +        api.fetchSearchAddresses { result in
Pior que foi mesmo, fazer as coisas cansado da nisso. Vou ajustar

2022-08-12 15:08 UTC, vitor-rc1 commented on solutions/devsprint-matheus-reis-3/DeliveryAppChallenge/Screens/Components/AddressListView/AddressListView.swift
> +    private let dataSource: AddressListDataSource
E conversamos sobre isso ontem, acabei deixando passar. Vou ajustar

2022-08-12 15:11 UTC, reisdev commented on solutions/devsprint-matheus-reis-3/DeliveryAppChallenge/Screens/AddressSearch/AddressSearchProtocols.swift
> +protocol AddressSearchViewModelDelegate: AnyObject {
Seguindo o padrão que vimos durante a sprint, é mais interessante nomear esse protocolo `AddressSearchViewModelPresentable`.

2022-08-16 19:22 UTC, reisdev requested changes

2022-08-16 19:22 UTC, reisdev commented on solutions/devsprint-matheus-reis-3/DeliveryAppChallenge/Screens/Components/AddressListView/AddressListView.swift
> +        self.dataSource = dataSource
O ideal(e mais comum) é deixar a atribuição do dataSource para quem for instanciar a view, assim como acontece na `tableView`. Então, ao invés de passar o parâmetro no `init`, a atribuição seria feita no `AddressListViewController`

2022-08-16 19:22 UTC, reisdev commented on solutions/devsprint-matheus-reis-3/DeliveryAppChallenge/Screens/Components/AddressListView/AddressListView.swift
> +        cell.addressCellViewModel = dataSource?.getAddressViewModel(at: indexPath) ?? AddressCellViewModel(title: String(), subtitle: String())
Já que a propriedade `addressCellViewModel` é opcional, não vejo necessidade de usar o operador `??` nesse caso. Você poderia, por exemplo, usar um `if let`, para garantir que o valor apenas seja atribuído caso o mesmo seja obtido do `dataSource`

2022-09-21 16:47 UTC, closed without merging