Network generic layer created and integration with api to get address…
devpass-tech/challenge-mvvm-delivery pull request #68
Opened 2023-01-25 17:19 UTC by Bruques

… response

2023-01-25 20:37 UTC, Bruques commented
Now, my integration is only to get address response

2023-01-25 21:20 UTC, reisdev requested changes

2023-01-25 21:20 UTC, reisdev commented on solutions/devsprint-matheus-reis-6/DeliveryAppChallenge/Screens/Home/HomeViewModel.swift
> +}
Remover este arquivo

2023-01-25 21:20 UTC, reisdev commented on solutions/devsprint-matheus-reis-6/DeliveryAppChallenge/Service/NetworkManager.swift
> +    func get<T: Decodable>(urlRequest: RequestProtocol, completion: @escaping (Result<T, NetworkError>) -> ()) {
Alterar o parâmetro `urlRequest: RequestProtocol` para `_ request: RequestProtocol`.

2023-01-25 21:20 UTC, reisdev commented on solutions/devsprint-matheus-reis-6/DeliveryAppChallenge/Service/DeliveryApi.swift
> +        self.networkManager.get(urlRequest: DeliveryRequest.addresses) { (result: Result<[Address], NetworkError>) in
Nesse contexto não é necessário usar o `self` nesse contexto.

2023-01-25 21:20 UTC, reisdev commented on solutions/devsprint-matheus-reis-6/DeliveryAppChallenge/Service/NetworkError.swift
> +    case decodedFailure
Renomear `decodedFailure` para `decodeFailure`

2023-01-25 21:20 UTC, reisdev commented on solutions/devsprint-matheus-reis-6/DeliveryAppChallenge/Screens/Home/HomeViewController.swift
> +
Remover essa linha em branco

2023-01-26 21:12 UTC, reisdev approved these changes

2023-01-26 21:13 UTC, merged